<script setup lang="ts">
import type { DecisionAnswer, DesignDecision } from '~/composables/useApi'

const route = useRoute()
const router = useRouter()
const sid = route.params.id as string
const api = useApi()

const decisions = ref<DesignDecision[]>([])
const answers = ref<Record<string, DecisionAnswer>>({})
const status = ref<'idle' | 'generating' | 'ready' | 'submitting' | 'failed'>('idle')
const progressMsg = ref('')
const error = ref<string | null>(null)
let timer: ReturnType<typeof setTimeout> | null = null

async function loadExisting() {
  const existing = await api.getDecisions(sid)
  if (existing.length) {
    decisions.value = existing
    for (const d of existing) {
      answers.value[d.id] = answers.value[d.id] ?? {
        decision_id: d.id, selected_option_id: null, freeform_answer: null,
      }
    }
    status.value = 'ready'
  }
}
await loadExisting()

async function poll(jobId: string) {
  try {
    const j = await api.getJob(sid, jobId)
    progressMsg.value = j.progress_message
    if (j.status === 'completed') {
      await loadExisting()
      status.value = 'ready'
      return
    }
    if (j.status === 'failed') {
      status.value = 'failed'
      error.value = j.error || 'Decision generation failed'
      return
    }
  } catch (e: any) {
    status.value = 'failed'
    error.value = e?.message || 'Polling error'
    return
  }
  timer = setTimeout(() => poll(jobId), 1500)
}

async function generate() {
  status.value = 'generating'
  error.value = null
  progressMsg.value = 'submitting...'
  try {
    const r = await api.generateDecisions(sid)
    poll(r.job_id)
  } catch (e: any) {
    status.value = 'failed'
    error.value = e?.data?.detail ?? e?.message ?? String(e)
  }
}

function isAnswered(d: DesignDecision): boolean {
  const a = answers.value[d.id]
  if (!a) return false
  return Boolean(a.selected_option_id || (d.allow_freeform && a.freeform_answer?.trim()))
}

const allAnswered = computed(() =>
  decisions.value.length > 0 && decisions.value.every(isAnswered),
)

async function submit() {
  status.value = 'submitting'
  try {
    await api.submitDecisionAnswers(sid, Object.values(answers.value))
    await router.push(`/sessions/${sid}/prompt`)
  } catch (e: any) {
    status.value = 'failed'
    error.value = e?.data?.detail ?? e?.message ?? String(e)
  }
}

onBeforeUnmount(() => { if (timer) clearTimeout(timer) })
</script>

<template>
  <div class="min-h-screen p-6 max-w-3xl mx-auto space-y-4">
    <UCard>
      <template #header>
        <h1 class="text-xl font-semibold">Design decisions</h1>
        <p class="text-sm text-neutral-500">
          Answers feed directly into the assembled prompt. Generated by DSPy from your
          confirmed source and destination profiles.
        </p>
      </template>

      <div v-if="!decisions.length && status === 'idle'" class="space-y-3">
        <p class="text-sm">No decisions generated yet.</p>
        <UButton color="primary" icon="i-lucide-sparkles" @click="generate">
          Generate decisions
        </UButton>
      </div>

      <div v-else-if="status === 'generating'" class="flex items-center gap-2 text-sm">
        <UIcon name="i-lucide-loader-circle" class="animate-spin" />
        {{ progressMsg || 'Generating...' }}
      </div>

      <div v-else-if="status === 'failed'" class="text-sm text-red-600">
        <UIcon name="i-lucide-circle-alert" class="mr-1" />
        {{ error }}
        <UButton size="xs" variant="soft" class="ml-3" @click="generate">Retry</UButton>
      </div>

      <div v-else class="space-y-6">
        <div v-for="d in decisions" :key="d.id" class="border-b border-neutral-200 dark:border-neutral-800 pb-4 last:border-0">
          <p class="font-medium">{{ d.question }}</p>
          <p v-if="d.rationale" class="text-xs text-neutral-500 mt-1">{{ d.rationale }}</p>
          <div class="mt-3 space-y-2">
            <label v-for="opt in d.options" :key="opt.id" class="flex items-start gap-2 text-sm cursor-pointer">
              <input
                type="radio"
                :name="d.id"
                :value="opt.id"
                v-model="answers[d.id].selected_option_id"
                class="mt-1"
              />
              <span>
                <span class="font-medium">{{ opt.label }}</span>
                <span v-if="opt.description" class="text-neutral-500"> — {{ opt.description }}</span>
              </span>
            </label>
            <UInput
              v-if="d.allow_freeform"
              v-model="answers[d.id].freeform_answer"
              placeholder="Or write a freeform answer..."
              class="mt-2"
            />
          </div>
        </div>
      </div>

      <template v-if="decisions.length && status !== 'generating'" #footer>
        <UButton
          color="primary"
          icon="i-lucide-arrow-right"
          :disabled="!allAnswered || status === 'submitting'"
          :loading="status === 'submitting'"
          label="Submit answers & build prompt"
          @click="submit"
        />
        <UButton
          variant="ghost" class="ml-2" icon="i-lucide-refresh-cw"
          @click="generate"
        >
          Re-generate
        </UButton>
      </template>
    </UCard>
  </div>
</template>
